<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: communications.proto

namespace Communications;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>communications.RestarauntInfo</code>
 */
class RestarauntInfo extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string name = 1;</code>
     */
    private $name = '';
    /**
     * Generated from protobuf field <code>string rating = 2;</code>
     */
    private $rating = '';
    /**
     * Generated from protobuf field <code>string cuisines = 3;</code>
     */
    private $cuisines = '';
    /**
     * Generated from protobuf field <code>string address = 4;</code>
     */
    private $address = '';
    /**
     * Generated from protobuf field <code>string time = 5;</code>
     */
    private $time = '';
    /**
     * Generated from protobuf field <code>string cft = 6;</code>
     */
    private $cft = '';
    /**
     * Generated from protobuf field <code>string ID = 7;</code>
     */
    private $ID = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $name
     *     @type string $rating
     *     @type string $cuisines
     *     @type string $address
     *     @type string $time
     *     @type string $cft
     *     @type string $ID
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Communications::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string name = 1;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Generated from protobuf field <code>string name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string rating = 2;</code>
     * @return string
     */
    public function getRating()
    {
        return $this->rating;
    }

    /**
     * Generated from protobuf field <code>string rating = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setRating($var)
    {
        GPBUtil::checkString($var, True);
        $this->rating = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string cuisines = 3;</code>
     * @return string
     */
    public function getCuisines()
    {
        return $this->cuisines;
    }

    /**
     * Generated from protobuf field <code>string cuisines = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setCuisines($var)
    {
        GPBUtil::checkString($var, True);
        $this->cuisines = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string address = 4;</code>
     * @return string
     */
    public function getAddress()
    {
        return $this->address;
    }

    /**
     * Generated from protobuf field <code>string address = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setAddress($var)
    {
        GPBUtil::checkString($var, True);
        $this->address = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string time = 5;</code>
     * @return string
     */
    public function getTime()
    {
        return $this->time;
    }

    /**
     * Generated from protobuf field <code>string time = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setTime($var)
    {
        GPBUtil::checkString($var, True);
        $this->time = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string cft = 6;</code>
     * @return string
     */
    public function getCft()
    {
        return $this->cft;
    }

    /**
     * Generated from protobuf field <code>string cft = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setCft($var)
    {
        GPBUtil::checkString($var, True);
        $this->cft = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string ID = 7;</code>
     * @return string
     */
    public function getID()
    {
        return $this->ID;
    }

    /**
     * Generated from protobuf field <code>string ID = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setID($var)
    {
        GPBUtil::checkString($var, True);
        $this->ID = $var;

        return $this;
    }

}

